# Run this file like so (from root of repo):
# docker-compose -f custom/docker-compose.yml up
version: "3.4"

services:
  samson:
    image: samson:ps-1.0.0
    network_mode: host
    dns: 10.110.3.220
    ports:
      - "9080:9080"
    environment:
      LDAP_BIND_PASSWORD_FILE: /home/appuser/ldap_pw
      DEFAULT_URL: "http://127.0.0.1:9080"
      DATABASE_URL: "mysql://127.0.0.1:3306"
      DATABASE_USER_FILE: /home/appuser/db_user
      DATABASE_PASSWORD_FILE: /home/appuser/db_pass
      SSH_AUTH_SOCK: "/ssh-agent"
      RAILS_LOG_TO_STDOUT: 1
      # RAILS_ENV: production
    # env_file: .env.bootstrap
    volumes:
      - $HOME/docker/samson/home:/home/appuser:ro
      - $SSH_AUTH_SOCK:/ssh-agent
